# Managed by repository-settings/app
# https://github.com/repository-settings/app

repository:
  description: "Knowledge graph data structures"
  homepage: "https://docs.rs/lattix"
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

  topics:
    - gnn
    - graph-algorithms
    - graph-learning
    - graph-neural-networks
    - knowledge-graph
    - knowledge-graphs
    - node2vec
    - pagerank
    - rdf
    - rust
    - temporal-graphs
